#!/usr/bin/env fish

function lucas 
  set -g prev $argv[2]
  set -g next (math $argv[1] + $argv[2]) 
  set -g count (math $count + 1)
end

set input $argv[1]
set threshold 6440026026380244498

if test $input -ge $threshold
  echo 91
  exit
end

if test $input -le 2
  echo $input
else
  set -g prev 2
  set -g next 1
  set -g count 1 

  while true 
    lucas $prev $next
    if test $next -gt $input
      echo $count
      exit
    end
  end
end
